---
deployment:
  tasks:
    - /bin/echo "Ran at $(date)" >> /home/runraga/deploy-hook.txt
    - /bin/mkdir -p /home/runraga/public_html/mill-bank/
    - /bin/echo "Hello from deploy $(date)" > /home/runraga/public_html/mill-bank/_deployed.txt
