---
deployment:
  tasks:
    - export DEPLOYPATH=/home/runraga/public_html/mill-bank/
    - /bin/echo "=== Deploy start: $(date) ===" >> /home/runraga/deploy.log
    - /bin/mkdir -p "$DEPLOYPATH"
    - /usr/bin/rsync -av --delete \
        --exclude '.git' \
        "$PWD/" "$DEPLOYPATH/" | /usr/bin/tee -a /home/runraga/deploy.log
    - /bin/echo "=== Deploy end: $(date) ===" >> /home/runraga/deploy.log